-- Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Create outfits table
CREATE TABLE outfits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  outfit_id TEXT UNIQUE NOT NULL,
  outfit_name TEXT NOT NULL,
  brand TEXT,
  category TEXT,
  gender TEXT,
  color TEXT,
  size_range TEXT,
  price NUMERIC,
  rating NUMERIC,
  description TEXT,
  occasion TEXT,
  season TEXT,
  image_file TEXT,
  links TEXT,
  embedding VECTOR(768)
);

-- Recommended: create an index for faster similarity searches. 
-- For vector columns, we can use ivfflat or hnsw.
CREATE INDEX ON outfits USING hnsw (embedding vector_cosine_ops);

-- Create a match function for semantic search
CREATE OR REPLACE FUNCTION match_outfits (
  query_embedding VECTOR(768),
  match_threshold FLOAT,
  match_count INT
)
RETURNS TABLE (
  id BIGINT,
  outfit_id TEXT,
  outfit_name TEXT,
  brand TEXT,
  category TEXT,
  gender TEXT,
  color TEXT,
  size_range TEXT,
  price NUMERIC,
  rating NUMERIC,
  description TEXT,
  occasion TEXT,
  season TEXT,
  image_file TEXT,
  links TEXT,
  similarity FLOAT
)
LANGUAGE sql
STABLE
AS $$
  SELECT
    outfits.id,
    outfits.outfit_id,
    outfits.outfit_name,
    outfits.brand,
    outfits.category,
    outfits.gender,
    outfits.color,
    outfits.size_range,
    outfits.price,
    outfits.rating,
    outfits.description,
    outfits.occasion,
    outfits.season,
    outfits.image_file,
    outfits.links,
    1 - (outfits.embedding <=> query_embedding) AS similarity
  FROM outfits
  WHERE 1 - (outfits.embedding <=> query_embedding) > match_threshold
  ORDER BY outfits.embedding <=> query_embedding
  LIMIT match_count;
$$;
